baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en" # Modify to change the default language/version of the site

title = "AWS Modernization Workshop Sample"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= "false"
uglyurls = "true"
enableEmoji = true

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page. 
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  #editURL = ""
  # Author of the site, will be used in meta information
  author = "James Bland"
  # Description of the site, will be used in meta information
  description = "AWS Modernization Workshop"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = true
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated. 
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it. 
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "mine"


[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]] 
name = "<i class='fas fa-graduation-cap'></i> Modernization Workshops"
url = "https://awsworkshop.io"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-tools'></i> VGS Blog"
url = "https://aws.amazon.com/blogs/apn/a-fintech-roadmap-to-data-security-and-compliance-with-vgs-and-aws/"
weight = 11

[[menu.shortcuts]]
name = "<i class='far fa-lightbulb'></i> Very Good Security"
url = "https://www.verygoodsecurity.com/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> VGS Marketplace"
url = "https://aws.amazon.com/marketplace/seller-profile?id=1c6092e5-40b6-41c5-bb91-aa6ed62ae9be"
weight = 21

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> VGS Vault"
url = "https://www.verygoodsecurity.com/docs/"
weight = 22

[[menu.shortcuts]]
name = "<i class='fas fa-chalkboard-teacher'></i> VGS Payment Optimization"
url = "https://www.verygoodsecurity.com/docs/payment-optimization/"
weight = 23

[markup]
  defaultMarkdownHandler = "Goldmark"
  [markup.Goldmark]
    hrefTargetBlank = true

[Languages] # Modify to change the language/version settings and/or version secondary extensions
[Languages.en]
title = "English"
weight = 1
languageName = "English"

[Languages.ee]
title = "Event Engine Setup"
weight = 2
languageName = "Event Engine Setup"
